apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: localhost-argocd
  namespace: argocd
spec:
  project: default

  source:
    chart: localhost-app
    repoURL: https://github.com/Timi-T/localhost-gitops
    targetRevision: 1.16.0
    path: localhost-app/
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
